# Config file for go-test-coverage github action.

profile: cover.short.profile,cover.long.profile
local-prefix: "github.com/vladopajic/go-test-coverage/v2"
threshold:
  file: 100
  total: 95
override:
  - threshold: 85
    path: badgestorer/cdn.go$
  - threshold: 50
    path: badgestorer/github.go$
exclude:
  paths:
    - main\.go$